services:
  - type: web
    name: mindscape-backend
    rootDir: backend-node
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: EMAIL_SMTP_URL
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: FILE_STORAGE_BUCKET
        sync: false
      - key: FILE_STORAGE_ENDPOINT
        sync: false